default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: import
      threads: <%= ENV.fetch("IMPORT_JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: archive
      threads: <%= ENV.fetch("ARCHIVE_JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: maintenance
      threads: <%= ENV.fetch("MAINTENANCE_JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: analysis
      threads: <%= ENV.fetch("ANALYSIS_JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: video_previews
      threads: <%= ENV.fetch("VIDEO_PREVIEW_JOB_THREADS", 2) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: derivatives
      threads: <%= ENV.fetch("DERIVATIVE_JOB_THREADS", 3) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5
    - queues: default
      threads: <%= ENV.fetch("DEFAULT_JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_PROCESSES", ENV.fetch("JOB_CONCURRENCY", 1)) %>
      polling_interval: 0.5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
